#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARTIFACT_DIR="${GAUSSIAN_LIC_ARTIFACT_DIR:-/tmp/gaussian_lic_artifact_gates}"
cd "${ROOT_DIR}"
rm -rf "${ARTIFACT_DIR}"
mkdir -p "${ARTIFACT_DIR}"

echo "[artifact] trajectory comparison"
cat >/tmp/gaussian_lic_baseline.tum <<'EOF'
0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
0.100000000 1.000000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
0.200000000 2.000000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
EOF
cat >/tmp/gaussian_lic_current.tum <<'EOF'
0.000000000 0.002000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
0.100000000 1.003000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
0.200000000 2.004000000 0.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000
EOF
./scripts/trajectory_compare.py \
  --baseline /tmp/gaussian_lic_baseline.tum \
  --current /tmp/gaussian_lic_current.tum \
  --output "${ARTIFACT_DIR}/trajectory_compare.json" \
  --max-rmse-m 0.01 \
  --max-mean-m 0.01 \
  --max-error-m 0.01
rg -q '"ok": true' "${ARTIFACT_DIR}/trajectory_compare.json"

echo "[artifact] point cloud comparison"
cat >/tmp/gaussian_lic_baseline.ply <<'EOF'
ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
0.000000000 0.000000000 0.000000000 255 32 16
1.000000000 0.000000000 0.000000000 255 32 16
2.000000000 0.000000000 0.000000000 255 32 16
EOF
cat >/tmp/gaussian_lic_current.ply <<'EOF'
ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
0.001000000 0.000000000 0.000000000 255 32 16
1.002000000 0.000000000 0.000000000 255 32 16
2.003000000 0.000000000 0.000000000 255 32 16
EOF
./scripts/pointcloud_compare.py \
  --baseline /tmp/gaussian_lic_baseline.ply \
  --current /tmp/gaussian_lic_current.ply \
  --output "${ARTIFACT_DIR}/pointcloud_compare.json" \
  --voxel-size 0 \
  --max-nearest-m 0.01 \
  --max-centroid-drift-m 0.01 \
  --max-chamfer-rmse-m 0.01 \
  --max-chamfer-mean-m 0.01 \
  --max-chamfer-max-m 0.01
rg -q '"ok": true' "${ARTIFACT_DIR}/pointcloud_compare.json"

echo "[artifact] baseline manifest"
rm -rf /tmp/gaussian_lic_baseline_manifest
mkdir -p /tmp/gaussian_lic_baseline_manifest/renders
cp /tmp/gaussian_lic_baseline.tum /tmp/gaussian_lic_baseline_manifest/trajectory.tum
cp /tmp/gaussian_lic_baseline.ply /tmp/gaussian_lic_baseline_manifest/point_cloud.ply
printf '{"tracking_hz": 10.0, "mapping_hz": 10.0, "mean_iteration_ms": 1.0}\n' \
  >/tmp/gaussian_lic_baseline_manifest/metrics.json
printf 'synthetic baseline run\n' >/tmp/gaussian_lic_baseline_manifest/run.log
printf 'synthetic render placeholder\n' >/tmp/gaussian_lic_baseline_manifest/renders/frame_000001.txt
./scripts/baseline_manifest.py \
  --baseline /tmp/gaussian_lic_baseline_manifest \
  --sequence synthetic_verify \
  --write \
  --json \
  >"${ARTIFACT_DIR}/baseline_manifest_stdout.json"
rg -q '"ok": true' /tmp/gaussian_lic_baseline_manifest/baseline_manifest.json
rg -q '"trajectory_poses": 3' /tmp/gaussian_lic_baseline_manifest/baseline_manifest.json
rg -q '"point_cloud_vertices": 3' /tmp/gaussian_lic_baseline_manifest/baseline_manifest.json
cp /tmp/gaussian_lic_baseline_manifest/baseline_manifest.json \
  "${ARTIFACT_DIR}/baseline_manifest.json"

echo "[artifact] reproduction report"
rm -rf /tmp/gaussian_lic_current_report
mkdir -p /tmp/gaussian_lic_current_report
cp /tmp/gaussian_lic_current.tum /tmp/gaussian_lic_current_report/trajectory.tum
cp /tmp/gaussian_lic_current.ply /tmp/gaussian_lic_current_report/point_cloud.ply
printf '{"tracking_hz": 9.8, "mapping_hz": 9.7, "mean_iteration_ms": 1.05}\n' \
  >/tmp/gaussian_lic_current_report/metrics.json
./scripts/reproduction_report.py \
  --baseline-dir /tmp/gaussian_lic_baseline_manifest \
  --current-dir /tmp/gaussian_lic_current_report \
  --sequence synthetic_verify \
  --output "${ARTIFACT_DIR}/reproduction_report.json" \
  --markdown "${ARTIFACT_DIR}/reproduction_report.md" \
  --max-trajectory-rmse-m 0.01 \
  --max-trajectory-mean-m 0.01 \
  --max-trajectory-error-m 0.01 \
  --pointcloud-voxel-size 0 \
  --max-nearest-m 0.01 \
  --max-centroid-drift-m 0.01 \
  --max-chamfer-rmse-m 0.01 \
  --max-chamfer-mean-m 0.01 \
  --max-chamfer-max-m 0.01
rg -q '"ok": true' "${ARTIFACT_DIR}/reproduction_report.json"
rg -q '| metrics | PASS |' "${ARTIFACT_DIR}/reproduction_report.md"

cat >"${ARTIFACT_DIR}/README.md" <<EOF
# Gaussian-LIC Artifact Gate Reports

Synthetic reports generated by scripts/verify_artifact_gates.sh.

- trajectory_compare.json
- pointcloud_compare.json
- baseline_manifest.json
- reproduction_report.json
- reproduction_report.md
EOF

echo "[artifact] reports: ${ARTIFACT_DIR}"
echo "[artifact] passed"
